# Generated by Django 3.0.8 on 2021-03-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyname_kanji', models.CharField(max_length=50, verbose_name='苗字漢字')),
                ('lastname_kanji', models.CharField(max_length=50, verbose_name='名前漢字')),
                ('familyname_kana', models.CharField(max_length=50, verbose_name='苗字カナ')),
                ('lastname_kana', models.CharField(max_length=50, verbose_name='名前カナ')),
                ('zipCode', models.CharField(max_length=255, verbose_name='郵便番号')),
                ('state', models.CharField(max_length=255, verbose_name='都道府県')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('buildingName', models.CharField(max_length=255, verbose_name='建物名')),
                ('phoneNumber', models.CharField(max_length=25, verbose_name='電話番号')),
                ('mailAdrress', models.CharField(max_length=255, verbose_name='メールアドレス')),
                ('stripeCode', models.CharField(blank=True, max_length=50, verbose_name='ストライプコード')),
                ('salesPrice', models.IntegerField()),
                ('taxPrice', models.IntegerField()),
                ('shippingPrice', models.IntegerField()),
                ('discountPrice', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='販売日')),
            ],
        ),
    ]
