# Generated by Django 3.0.8 on 2021-03-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='available',
            field=models.BooleanField(default=False, verbose_name='発送済み'),
        ),
    ]
