# Generated by Django 3.0.8 on 2021-03-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_intax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': '店舗カテゴリー', 'verbose_name_plural': 'shop_categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': '商品', 'verbose_name_plural': 'products'},
        ),
        migrations.AddField(
            model_name='product',
            name='cookingUrl',
            field=models.CharField(blank=True, max_length=10000, verbose_name='調理動画'),
        ),
        migrations.AddField(
            model_name='product',
            name='descriptionContent1',
            field=models.TextField(blank=True, verbose_name='説明内容1'),
        ),
        migrations.AddField(
            model_name='product',
            name='descriptionContent2',
            field=models.TextField(blank=True, verbose_name='説明タイトル2'),
        ),
        migrations.AddField(
            model_name='product',
            name='descriptionContent3',
            field=models.TextField(blank=True, verbose_name='説明内容3'),
        ),
        migrations.AddField(
            model_name='product',
            name='descriptionContent4',
            field=models.TextField(blank=True, verbose_name='説明内容4'),
        ),
        migrations.AddField(
            model_name='product',
            name='descriptionImage1',
            field=models.ImageField(blank=True, upload_to='product', verbose_name='説明画像1'),
        ),
        migrations.AddField(
            model_name='product',
            name='descriptionImage2',
            field=models.ImageField(blank=True, upload_to='product', verbose_name='説明画像2'),
        ),
        migrations.AddField(
            model_name='product',
            name='descriptionImage3',
            field=models.ImageField(blank=True, upload_to='product', verbose_name='説明画像3'),
        ),
        migrations.AddField(
            model_name='product',
            name='descriptionImage4',
            field=models.ImageField(blank=True, upload_to='product', verbose_name='説明画像4'),
        ),
        migrations.AddField(
            model_name='product',
            name='descriptionTitle1',
            field=models.CharField(blank=True, max_length=255, verbose_name='説明タイトル1'),
        ),
        migrations.AddField(
            model_name='product',
            name='descriptionTitle2',
            field=models.CharField(blank=True, max_length=255, verbose_name='説明タイトル2'),
        ),
        migrations.AddField(
            model_name='product',
            name='descriptionTitle3',
            field=models.CharField(blank=True, max_length=255, verbose_name='説明タイトル3'),
        ),
        migrations.AddField(
            model_name='product',
            name='descriptionTitle4',
            field=models.CharField(blank=True, max_length=255, verbose_name='説明タイトル4'),
        ),
        migrations.AddField(
            model_name='product',
            name='hoverImage',
            field=models.ImageField(blank=True, upload_to='product', verbose_name='ホバー画像'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, upload_to='product', verbose_name='画像2枚目'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, upload_to='product', verbose_name='画像3枚目'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='商品説明'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product', verbose_name='TOP画像'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inTax',
            field=models.PositiveIntegerField(default=200, verbose_name='内消費税'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='価格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(verbose_name='在庫'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='変更日'),
        ),
    ]
