# Generated by Django 3.0.8 on 2021-03-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210307_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cartDescription',
            field=models.CharField(blank=True, max_length=100, verbose_name='カート用説明'),
        ),
    ]
