# Generated by Django 3.0.8 on 2021-03-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210308_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A1', models.IntegerField(default=1584, verbose_name='沖縄')),
                ('A2', models.IntegerField(default=1364, verbose_name='北海道・九州')),
                ('A3', models.IntegerField(default=1144, verbose_name='中国・四国')),
                ('A4', models.IntegerField(default=1034, verbose_name='北東方・関西')),
                ('A5', models.IntegerField(default=1034, verbose_name='南東北・関東・信越・北陸・中部')),
            ],
            options={
                'verbose_name_plural': '配送料',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'カテゴリー'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name_plural': '商品データ'},
        ),
    ]
