# Generated by Django 3.0.8 on 2021-03-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210311_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingprice',
            name='A1',
        ),
        migrations.RemoveField(
            model_name='shippingprice',
            name='A2',
        ),
        migrations.RemoveField(
            model_name='shippingprice',
            name='A3',
        ),
        migrations.RemoveField(
            model_name='shippingprice',
            name='A4',
        ),
        migrations.RemoveField(
            model_name='shippingprice',
            name='A5',
        ),
        migrations.AddField(
            model_name='shippingprice',
            name='area_name',
            field=models.CharField(default='test', max_length=20, unique=True, verbose_name='エリア名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingprice',
            name='shipping_price',
            field=models.IntegerField(default=123, verbose_name='配送料'),
            preserve_default=False,
        ),
    ]
