# Generated by Django 3.0.8 on 2021-03-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210311_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingprice',
            name='description',
            field=models.TextField(blank=True, verbose_name='エリア説明'),
        ),
    ]
